Rewrite chapter 6.10 struct expressions chapter
ferrocene/specification pull request #195
Opened 2022-08-02 13:24 UTC by Veykril

Fixes https://github.com/ferrocene/specification/issues/185

2022-08-02 13:39 UTC, Veykril commented
This skips over talking about unit variants and unit structs in path expressions, opened https://github.com/ferrocene/specification/issues/196 for that

2022-08-02 17:14 UTC, kirtchev-adacore requested changes

2022-08-03 13:25 UTC, kirtchev-adacore approved these changes

2022-08-03 13:25 UTC, kirtchev-adacore commented
bors merge

2022-08-03 13:28 UTC, merged