Fully specify behavior of unary operators
ferrocene/specification pull request #329
Opened 2022-10-04 16:07 UTC by jonas-schievink

2022-10-04 17:01 UTC, kirtchev-adacore requested changes

2022-10-04 17:01 UTC, kirtchev-adacore commented on src/expressions.rst
> +   :t:`negation expression` evaluates to the value of the operand, with its sign
the :t:`value` of the :t:`operand`

2022-10-04 17:01 UTC, kirtchev-adacore commented on src/expressions.rst
> +      If the result of the negation does not fit within the range of the
I would replace "the negation" with "the :t:`negation expression`".

2022-10-04 17:01 UTC, kirtchev-adacore commented on src/expressions.rst
> +   :t:`negation expression` evaluates to the value of the operand, with its sign
the :t:`value` of the :t:`operand`

2022-10-05 15:06 UTC, kirtchev-adacore commented
bors merge

2022-10-06 13:57 UTC, pietroalbini commented
bors retry

2022-10-06 14:00 UTC, merged