Update to 1.79
ferrocene/specification pull request #500
Opened 2024-06-14 09:17 UTC by Veykril

Builds on top of #499

2024-06-14 13:15 UTC, pietroalbini requested changes

2024-06-14 13:15 UTC, pietroalbini commented on src/program-structure-and-compilation.rst
> +library.
I am quite confused by this: whether a crate is a binary crate or a library crate is just determined by the `--crate-type` flag or the `#![crate_type]` attribute. You can also have executables with `#![no_main]` (if you define your own entry point the linker can find).

2024-06-14 13:27 UTC, Veykril commented on src/functions.rst
> +a :t:`crate root module` of a :t:`crate`.
I have been tricked by the playground and me not reading the error message properly

2024-07-03 08:00 UTC, pietroalbini requested changes

2024-07-03 10:13 UTC, pietroalbini commented on src/attributes.rst
>  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nit: the length of the header underline is not the same. I *think* it might cause Sphinx build to fail.

2024-07-03 10:28 UTC, pietroalbini approved these changes
bors merge

2024-07-03 10:29 UTC, merged