Update changelog for 1.81.0
ferrocene/specification pull request #522
Opened 2024-09-09 10:15 UTC by Veykril

2024-09-23 13:14 UTC, Hoverbear submitted a review, later dismissed

2024-09-23 15:46 UTC, pietroalbini requested changes

2024-09-23 15:46 UTC, pietroalbini commented on src/changelog.rst
> +  * No change: lints are not part of the FLS
We need to add the attribute to the list in https://spec.ferrocene.dev/attributes.html#built-in-attributes.

2024-09-24 12:52 UTC, pietroalbini approved these changes
bors merge

2024-09-24 12:53 UTC, merged