Update to 1.83
ferrocene/specification pull request #536
Opened 2024-12-09 12:58 UTC by Veykril

Builds atop of #529

2024-12-09 14:58 UTC, tshepang requested changes

2024-12-09 14:58 UTC, tshepang commented on src/types-and-traits.rst
> +       $$'$$  (NonKeywordIdentifier | RawIdentifierKeyword)
```suggestion
       $$'$$ (NonKeywordIdentifier | RawIdentifierKeyword)
```

2024-12-09 14:58 UTC, tshepang commented on src/types-and-traits.rst
> +A :t:`enum variant` is subject to :t:`visible emptiness` when the :t:`type` of at least one of the :t:`enum variant`'s visible <visibility> :t:`[field]s` is subject to :t:`visible emptiness`.
```suggestion
A :t:`enum variant` is subject to :t:`visible emptiness` when the :t:`type` of at least one of the :t:`enum variant`'s :t:`visible <visibility>` :t:`[field]s` is subject to :t:`visible emptiness`.
```

2024-12-09 14:58 UTC, tshepang commented on src/types-and-traits.rst
> +  The :t:`type` is an :t:`enum type` not subject to :t:`attribute` :c:`non_exhaustive` with all :t:`[enum variant]s` are subject to :t:`visible emptiness`.
is this what is meant
```suggestion
  The :t:`type` is an :t:`enum type` not subject to :t:`attribute` :c:`non_exhaustive` where all :t:`[enum variant]s` are subject to :t:`visible emptiness`.
```

2024-12-09 14:58 UTC, tshepang commented on src/macros.rst
> +  :t:`Fragment specifier` **expr** and **expr** requires an :t:`expression` that is not an :t:`underscore expression` or :t:`const block expression`.
```suggestion
  :t:`Fragment specifier` **expr** and **expr_2021** requires an :t:`expression` that is not an :t:`underscore expression` or :t:`const block expression`.
```

2024-12-09 14:58 UTC, tshepang commented on src/patterns.rst
> +matching a :t:`value` of a its :t:`type`
```suggestion
matching a :t:`value` of its :t:`type`
```

2024-12-09 14:58 UTC, tshepang commented on src/patterns.rst
> +  An :t:`enum variant` of an :t:`enum type` with zero or more :t:`[visibly empty enum variant]s` and one non-:t:`visibly empty enum variant` where the :t:`[type]s` of all :t:`[field]s` are not subjec
```suggestion
  An :t:`enum variant` of an :t:`enum type` with zero or more :t:`[visible empty enum variant]s` and one non-:t:`visible empty enum variant` where the :t:`[type]s` of all :t:`[field]s` are not subject to :t:`visible emptiness`
```

2024-12-09 14:58 UTC, tshepang commented on src/patterns.rst
> +    An :t:`enum variant` of an :t:`enum type` with zero or more :t:`[visibly empty enum variant]s` and one non-:t:`visibly empty enum variant` where the :t:`[type]s` of all :t:`[field]s` are not subj
```suggestion
    An :t:`enum variant` of an :t:`enum type` with zero or more :t:`[visible empty enum variant]s` and one non-:t:`visible empty enum variant` where the :t:`[type]s` of all :t:`[field]s` are not subject to :t:`visible emptiness`.
```

2024-12-10 09:04 UTC, Veykril commented on src/types-and-traits.rst
> +  The :t:`type` is an :t:`enum type` not subject to :t:`attribute` :c:`non_exhaustive` with all :t:`[enum variant]s` are subject to :t:`visible emptiness`.
yes

2024-12-10 09:20 UTC, tshepang approved these changes
bors merge

2024-12-10 09:22 UTC, merged